"""Stable serialization helpers for ZRC SDK error return values."""

# The Python bindings currently expose only a subset of ZRCSDKError members.
# Keep the values used by controller error responses here so callers never have
# to rely on pybind11's unhelpful ``ZRCSDKError.???`` representation.
ZRCSDK_ERROR_NAMES = {
    0: "ZRCSDKERR_SUCCESS",
    1: "ZRCSDKERR_INTERNAL_ERROR",
    2: "ZRCSDKERR_SERVICE_UNINITIALIZE",
    3: "ZRCSDKERR_NO_PERMISSION",
    4: "ZRCSDKERR_FEATURE_DISABLED",
    5: "ZRCSDKERR_ZR_NO_CAPABILITY",
    6: "ZRCSDKERR_INVALID_PARAMETER",
    7: "ZRCSDKERR_EVALUATION_DATE_EXPIRED",
    8: "ZRCSDKERR_API_NOT_SUPPORT_IN_WEBINAR",
    9: "ZRCSDKERR_API_WRONG_USAGE",
    10: "ZRCSDKERR_ALREADY_IN_THIS_STATE",
    11: "ZRCSDKERR_NOT_CONNECT_TO_ZOOMROOM",
    12: "ZRCSDKERR_HOST_WITHOUT_CAPABILITY",
    13: "ZRCSDKERR_HOST_NOT_IN_MEETING",
    14: "ZRCSDKERR_CAN_NOT_PERFORM_ACTION",
    15: "ZRCSDKERR_API_NOT_SUPPORT_IN_WEBINAR_BACKSTAGE",
    16: "ZRCSDKERR_REQUEST_HAS_BEEN_RESPONSED",
    17: "ZRCSDKERR_WEB_SETTINGS_LOCKED",
    50: "ZRCSDKERR_API_NOT_SUPPORT_IN_MEETING",
    51: "ZRCSDKERR_API_NOT_SUPPORT_IN_BO",
    52: "ZRCSDKERR_API_NOT_SUPPORT_IN_WEBINAR_BO",
    53: "ZRCSDKERR_API_NOT_SUPPORT_IN_WEBINAR_DEBRIEF_SESSION",
    54: "ZRCSDKERR_API_NOT_SUPPORT_IN_SWITCHING_MEETING",
    55: "ZRCSDKERR_API_NOT_SUPPORT_IN_SIMULIVE_WEBINAR",
    200: "ZRCSDKERR_INVALID_MEETING",
    201: "ZRCSDKERR_INVALID_MEETING_NUMBER",
    220: "ZRCSDKERR_ALREADY_IN_MEETING",
    221: "ZRCSDKERR_NOT_IN_MEETING",
    222: "ZRCSDKERR_NOT_IN_WEBINAR",
    223: "ZRCSDKERR_NOT_IN_PSTN_CALLOUT_MEETING",
    224: "ZRCSDKERR_NOT_IN_E2EE_Meeting",
    225: "ZRCSDKERR_NOT_IN_INTEGRATION_MEETING",
    226: "ZRCSDKERR_NOT_IN_WEBINAR_PRACTICE_SESSION",
    230: "ZRCSDKERR_IN_E2EE_MEETING",
    231: "ZRCSDKERR_IN_WAITING_ROOM",
    350: "ZRCSDKERR_RECORDING_NOT_AVAILABLE_IN_MEETING",
    351: "ZRCSDKERR_NOT_CONFIRM_START_RECORDING_DISCLAIMER",
    352: "ZRCSDKERR_NOT_SET_RECORDING_NOTIFICATION_EMAIL",
    353: "ZRCSDKERR_NO_NEED_TO_PROMPT_START_RECORDING_DISCLAIMER",
    700: "ZRCSDKERR_AIC_MEETING_SUMMARY_DISABLED",
    701: "ZRCSDKERR_AIC_MEETING_QUERY_DISABLED",
    702: "ZRCSDKERR_AIC_NO_PRIVILEGE_SETTING_ITEM",
    703: "ZRCSDKERR_AIC_INVALID_PRIVILEGE_SETTING_ITEM",
    704: "ZRCSDKERR_AIC_ALREADY_SET_MEETING_SUMMARY_NOTIFY_EMAIL",
    705: "ZRCSDKERR_AIC_NOT_SET_MEETING_SUMMARY_NOTIFY_EMAIL",
}


def zrcsdk_error_name(result) -> str:
    """Return a stable SDK error name, including for unbound enum members."""
    code = int(result)
    known_name = ZRCSDK_ERROR_NAMES.get(code)
    if known_name:
        return known_name

    bound_name = getattr(result, "name", None)
    if isinstance(bound_name, str) and bound_name.startswith("ZRCSDKERR_"):
        return bound_name

    return f"Unknown({code})"
